services:
  mysql:
    image: 'mysql:latest'
    container_name: db
    environment:
      - MYSQL_DATABASE=course_mapping
      - MYSQL_ROOT_PASSWORD=thanhhuyenc2pt

    ports:
      - '3302:3306'
  app:
    build: .
    container_name: app
    ports:
      - "8181:8000"
    depends_on:
      - mysql
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://172.22.0.2:3306/course_mapping?useSSL=false",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "thanhhuyenc2pt"
            }'
#  flask_server:
#    image: ...
#  python_server:
#    image: ...
#    container_name: ...
#    ports:
#      - "5000:5000"
#volumes:
#  mysql-data:
